echo "*************************************************"
echo  $GO_SERVER_URL
echo  $GO_PIPELINE_GROUP_NAME
echo  $GO_ENVIRONMENT_NAME
echo  $PROJECT_NAME
echo  $GO_TRIGGER_USER
echo  $GO_PIPELINE_NAME
echo  $GO_PIPELINE_COUNTER
echo  $GO_PIPELINE_LABEL
echo  $GO_STAGE_NAME
echo  $GO_STAGE_COUNTER
echo  $GO_JOB_NAME
echo  $GO_REVISION
echo  $GO_TO_REVISION
echo  $GO_FROM_REVISION
echo  $GO_MATERIAL_URL
echo  $GO_MATERIAL_BRANCH
echo  $GO_MATERIAL_HAS_CHANGED
echo "*************************************************"
